version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    environment:
      - DB_HOST=db  
      - DB_PORT=5433
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASSWORD=yourpassword
    depends_on:
      - db  

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data  #
    ports:
      - "5433:5433"

volumes:
  postgres_data:  
